# Generated by Django 4.0.3 on 2022-04-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0002_residence_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('user_request', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='residences.residence')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='residences.room')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
